### ISSUE TITLE
System.TypeLoadException: Could not load type 'Luminous.Code.Extensions.Strings.StringExtensions' from assembly 'Luminous.Code.Core, Version=1.4.2.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/extensibility-logs#13]
### Installed product versions
- Visual Studio: 2019
- This extension: 1.6

### Description

Error when clicking on VSIX Installer log

### Steps to recreate
1. install the extension
2. click on` VSIX Installer log` from your extension

### Current behavior

I get this exception:

```
System.TypeLoadException: Could not load type 'Luminous.Code.Extensions.Strings.StringExtensions' from assembly 'Luminous.Code.Core, Version=1.4.2.0, Culture=neutral, PublicKeyToken=null'.
   at ExtensibilityLogs.Commands.Logs.VsixInstallerLogCommand.<ExecuteAsync>d__2.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at ExtensibilityLogs.Commands.Logs.VsixInstallerLogCommand.ExecuteAsync(OleMenuCmdEventArgs e)
   at Community.VisualStudio.Toolkit.BaseCommand`1.<>c__DisplayClass14_0.<<Execute>b__0>d.MoveNext()
```

### Expected behavior

no exception

**Comment by yannduran** [comment]
Thanks Anrdé, 

I noticed this as well. But it's not a problem with _**Extensibility Tools v1.6**_ (the most recent update) as the problem can occur in the previous version as well, and that had not been changed for almost 2 years. Rather it would appear that some behavior of VS , or possibly the VSIX installer, has changed and is no longer releasing the installer log file as it used to do.

Where are you seeing this exception text? In an error dialog box? If it's an unhandled exception, then I'd be concerned, but if it's being correctly reported in a message box then there's not really much that I can do about it.

Sometimes a restart of VS will release it, sometimes the file will be become accessible at a later time in the same VS session.

**Comment by MagicAndre1981** [comment]
> Where are you seeing this exception text? In an error dialog box? If it's an unhandled exception, then I'd be concerned, but if it's being correctly reported in a message box then there's not really much that I can do about it.

I see this in output Window of Visual Studio after clicking the button

**Comment by yannduran** [comment]
So unless you go looking in the Output Window, you don't see this message?

Does an _Extensibility Logs_ modal error dialog message pop up? If so, what message does it display?

Is it the only button that this happens with?

**Comment by MagicAndre1981** [comment]
> So unless you go looking in the Output Window, you don't see this message?

correct

> Does an _Extensibility Logs_ modal error dialog message pop up? If so, what message does it display?

no error dialog. I was confused that nothing happens and found the error message in output.

> Is it the only button that this happens with?

from what I see yes. Activitylog opens fine

**Comment by yannduran** [comment]
I'll release a new update when the toolkit issue is resolved.

**Comment by MagicAndre1981** [comment]
the toolkit issue is marked as closed and new nugets are released.

**Comment by MagicAndre1981** [comment]
ok, this is the same issue like the toolkit issue. I have your `Luminous.Code.Core.dll` in 2 versions and your` ExtensibilityLogs` tries to run code that the old` Luminous.Code.Core.dll` from `StartPage+` doesn't include. 

I asked @madskristensen in [my issue with his extension](https://github.com/madskristensen/Tweakster/issues/76) about some details about this VS bug/issue with loading DLLs in 2 different versions

**Comment by MagicAndre1981** [comment]
Ok, Mads replyed that you need to add strongname to the shared dll.

**Comment by yannduran** [comment]
I'm aware of all of this André. I'm involved in the Community Toolkit, and I see all of the notifications about it. But thanks for passing it on.

**Comment by MagicAndre1981** [comment]
any update on this? Can we get an update to fix it?

**Comment by MagicAndre1981** [comment]
any update on this?

**Comment by MagicAndre1981** [comment]
now that you are back @yannduran , can you please release a fix for this?

**Comment by yannduran** [comment]
The VS 2022 version that I've almost finished working on doesn't currently use that library anymore. There'll be a preview available on the [VSIX Gallery](https://www.vsixgallery.com/) soon for people to test before the final version gets uploaded to the marketplace.

I may be _back_, but not to 100%. So I can only work on this stuff when I can. I'm truly sorry for the delays, but I can only do what I can do.

**Comment by yannduran** [comment]
There's a preview version you can try out [here](https://www.vsixgallery.com/extension/b3e27022-cd5d-41f1-af64-3bba7be3f544), but you'll need to uninstall it when the final version's uploaded to the gallery.

**Comment by yannduran** [comment]
@MagicAndre1981 did you try it out?

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 did you try it out?

yes, this version works, but this is expected as there is no 2022 version of StartPage+ which shares this common lib so if only 1 DLL is found there is no issue. 

I need a fixed 2019 version of StartPage+ and ExtensibilityLogs to test if it really works

**Comment by yannduran** [comment]
No 2022 version of any ported extensions will be using that separate Nuget package anymore (at least not for the foreseeable future, if at all).

Are you still using VS 2019 as well as VS 2022?

**Comment by MagicAndre1981** [comment]
I don't actively use 2022 as it is completely unusable without StartPage+ , I only run it for testings in a VM

**Comment by yannduran** [comment]
It's coming! I've reproduced the UI, I just need to implement the functionality. I haven't been able to spend as much time at my desk as I'd like, but it's getting there.

Believe me, I'm lost without it too!

**Comment by MagicAndre1981** [comment]
can you please fix this for 2019? 2022 is buggy as hell and will not be an option for productive usage in the next time

**Comment by MagicAndre1981** [comment]
ok, as future is now VS2022 I can close this as 64Bit version of Start Page+ and Extensibility Logs work fine now at same time.

**Comment by yannduran** [comment]
Yeah, in the 64-bit version of the extensions, I removed reliance on the `Luminous Code` Nuget package. It means that I have duplicated code now, which I don't like. But it at least allows the extensions to co-exist.

You explained what needed to be done quite well. I was just too ill to do anything about it.
