### ISSUE TITLE
Conflict warnings emitted with only 2 VS SDK package references added to the project

### ISSUE THREAD

**Issue by yannduran** [luminous-software/extensibility-logs#3]
### Installed product versions
- Visual Studio: 2019 v16.0.0 Preview 2.2
- This extension: v0.1.0

### Description
Only the following two VS SDK package references have been added to the project:

`Madskristensen.VisualStudio.SDK v16.0.81-pre 2`
`Microsoft.VSSDK.BuildTools v16.0.298`

 This causes two package-related conflict warnings to be emitted.

### Current behavior
Warning MSB3277: Found conflicts between different versions of "Microsoft.VisualStudio.ComponentModelHost" that could not be resolved. 

Warning MSB3277: Found conflicts between different versions of 
"Microsoft.VisualStudio.Text.Data" that could not be resolved.

### Expected behavior
No warning errors

**Comment by yannduran** [comment]
@madskristensen Any ideas?

**Comment by madskristensen** [comment]
Don't use the 16.0 stuff. Go with 15.8 instead

**Comment by yannduran** [comment]
Thanks!
