### ISSUE TITLE
Add commands to "View" top menu

### ISSUE THREAD

**Issue by madskristensen** [luminous-software/extensibility-logs#5]
For people who don't want to add more toolbars or don't have any visible toolbars at all, could we get a _View -> Extensibility Logs -> &lt;the log commands&gt;_ flyout menu as well?

**Comment by yannduran** [comment]
Yeah sure! That's a good idea!

**Comment by yannduran** [comment]
@madskristensen This has been added in v1.2 - thanks for the suggestion!
