### ISSUE TITLE
Wrong Project Repo Link in Marketplace?

### ISSUE THREAD

**Issue by spottedmahn** [luminous-software/extensibility-logs#9]
### Installed product versions
- Visual Studio: N/A
- This extension: N/A

### Description

https://marketplace.visualstudio.com/items?itemName=YannDuran.ExtensibilityLogs

![image](https://user-images.githubusercontent.com/14079228/58712794-4902e800-838f-11e9-958a-0ba1398e177b.png)

### Steps to recreate
1. Go to the marketplace

### Current behavior
Current link is to the [developer-news repo](https://github.com/luminous-software/developer-news)

### Expected behavior
Link to this repo

**Comment by yannduran** [comment]
I'm so sorry Michael. I don't know how I missed this.

I really appreciate you taking the time to let me know about this. I've fixed it now. 

Thanks again!

**Comment by spottedmahn** [comment]
>I don't know how I missed this

No worries, it happens 😀

>I really appreciate you taking the time to let me know about this. I've fixed it now.

You're welcome and awesome! 👏

**Comment by spottedmahn** [comment]
looks good 👍

![image](https://user-images.githubusercontent.com/14079228/64078849-1cbc7780-ccae-11e9-957a-34e8c61412c6.png)
